spring.application.name=crud-service

spring.datasource.url=jdbc:h2:mem:crud;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.oauth.client-id=crud-client
springdoc.swagger-ui.oauth.client-secret=crud-secret
